version: '3.8'

services:
  scraper:
    build: .
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    command: "python /app/src/steam_scraper.py"

  duckdb_setup:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: ./run_duckdb.sh

  dbt:
    build: .
    volumes:
      - ./steam_games_dbt:/app/steam_games_dbt
      - ./duckdb:/app/duckdb
    working_dir: /app/steam_games_dbt
    entrypoint: ["dbt"]
    command: run
