steam_games_dbt:
  outputs:
    dev:
      type: duckdb
      path: /app/duckdb/steam_games.duckdb
      threads: 1

    prod:
      type: duckdb
      path: /app/duckdb/steam_games.duckdb
      threads: 4

  target: dev
